# Generated by Django 4.1.1 on 2022-10-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_clue_rename_words_word"),
    ]

    operations = [
        migrations.DeleteModel(name="Clue",),
    ]
